#!/bin/bash
# Set up automatic daytime scheduling using cron

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⏰ SETTING UP DAYTIME SCHEDULE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
START_SCRIPT="$SCRIPT_DIR/start_daytime.sh"

echo "This will set up automatic bot scheduling:"
echo "  • Start at 6:00 AM"
echo "  • Stop at 10:00 PM"
echo "  • Runs Monday-Sunday"
echo ""
echo "Cron jobs to add:"
echo ""
echo "# Kalshi Bot - Start at 6am"
echo "0 6 * * * $START_SCRIPT >> $SCRIPT_DIR/cron.log 2>&1"
echo ""
echo "# Kalshi Bot - Stop at 10pm"
echo "0 22 * * * pkill -f 'python.*bot.py' >> $SCRIPT_DIR/cron.log 2>&1"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "To set up automatically, run:"
echo "  crontab -e"
echo ""
echo "Then paste the two lines above."
echo ""
echo "Or run manually:"
echo "  ./start_daytime.sh    (runs bot if 6am-10pm)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
